### ISSUE TITLE
SM - Historical data inaccurate and monthly/YTD score not calculating correctly

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#10]
For Kim Padgett - MG number 2053230, client name: International Union of Operating Engineers

Historical data is inacurrate and scores are not correct

**Comment by WorkMAE** [comment]
Will check to make sure data was imported properly.

**Comment by kartikbshukla** [comment]
Reached out to Kim to have her check.  Looks okay from my view.
