### ISSUE TITLE
ALL - Monthly Activity For The Year section changes

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#13]
- Make sure "Is Currently Active" check mark synchs with whether sam is active in the current month for that client
- Remove "Select All" and "Select None" options

**Comment by kartikbshukla** [comment]
"Select All" and "Select None" options still remain.  Confusing for users as this is not something they can choose.

**Comment by WorkMAE** [comment]
Will remove the Select All/None boxes.  The checkboxes are now properly updating according to the Current SAM for the month.
