### ISSUE TITLE
Incorrect SAMs under Team Leads

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#16]
- SAMs like "TBD1" and "See Comments" displayed.  Which field are you using?  Looks like you are not using the SAM_Month.
-Ben Clark shows up under Maureen

**Comment by WorkMAE** [comment]
This is not an issue with the report, its an issue with the Client File.  

If there are things like TBD1, TBD2, TBD3, See Comments  as SAM's when the Team Lead is listed, they are going to show up on there.  

My suggestion is to clean up the client file if you don't want these showing up.

**Comment by kartikbshukla** [comment]
But Ben is showing up under Maureen.  Clearly a mapping issue there.

Also for a client to be pending is a valid business use case.  We need to be able to deal with that.

**Comment by WorkMAE** [comment]
Again, its a mapping issue on the client file.  Ben is listed as a SAM under Maureen.  Fix the issue in the client file.
