### ISSUE TITLE
TL/AD - Toggle Issues Button disappears when returning to homepage

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#18]

**Comment by WorkMAE** [comment]
For some reason this appears to be an access issue...if you click the mouse all the way to the left of the screen next to the accounts when the button isn't visible,  it scrolls back all the way over---Again, this is likely due to the Scroll in scroll I am looking to get resolved.

**Comment by kartikbshukla** [comment]
I tried using the work around of click on the left side of the screen but it didn't work

**Comment by WorkMAE** [comment]
This should now be fixed as of Version 0.98a...Toggle Button no longer goes off the page
