### ISSUE TITLE
ALL - Averages not calculating correctly *SHOWSTOPPER*

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#25]
Tier 1 monthly average, Tier 2 monthly average, and Total Monthly, Average, and all YTD averages are not calculating correctly.  Based on points/caps.  Refer to documentation shared on how to correctly calculate scores.

**Comment by WorkMAE** [comment]
This should be corrected as of now.  Found instances in the Excel scorecard which aren't calculating correctly and once I changed those, all scores and averages were correct in every instance I checked...
