### ISSUE TITLE
AD - Error messages when updating a month for a client where SAM is now NOT Active for that month

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#29]
Also seeing append isntead of update query..not sure if thats what its supposed to be?

![error2_922](https://user-images.githubusercontent.com/31935414/30756740-6e95d9a6-9fbb-11e7-9db9-e848e833bc92.png)
![error1_922](https://user-images.githubusercontent.com/31935414/30756741-6ea3e2ee-9fbb-11e7-8181-4ea176c94fa7.png)

**Comment by maerman** [comment]
This should be fixed in release 0.98a
