### ISSUE TITLE
SAM - CMB-ISB-CRE table not linking correctly

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#42]
Error message on load and clients do not load.

![cmb isb](https://user-images.githubusercontent.com/31935414/32752712-1db6c4ac-c8c2-11e7-9719-8468bb87964c.PNG)

**Comment by WorkMAE** [comment]
Simply an error connecting to SharePoint, nothing I can do, Sharepoint might be down at the time
