### ISSUE TITLE
SAM (Sam View) - Current Month Score Not Correct

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#47]
The May CEM Score – Curr Month for May shows 5.79% when all the values show 0.  As I don’t think the NII/NFI has any information for the current month and the BR Survey scores would be in April and not included yet, it seems the value should be 0.00%

![current month score bug pic](https://user-images.githubusercontent.com/31935414/39829670-2c698ba0-538d-11e8-8681-c55bbd0b0da0.png)

**Comment by WorkMAE** [comment]
This is correct because there are still NFI/NII values...5.79% is equivalent to 1.5 points.
