### ISSUE TITLE
SAM (Client View) - Individual months not showing specific numbers

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#48]
It appears that the individual month information is not showing that months specific numbers.  Here are the reason I share this.

1.	In January, I could not have 2 in the Months Touched column when we are only looking at the first month of the year.
2.	NYK (last one on the list) was not active in January for me
3.	Oth Client Eng shows 9 in the month of January when I had 0 for adidas.  I had no entries in CV in January so all the numbers should be either 0 because you are solely using CV data or they should be the values entered on the spreadsheet if those were input into the database.

![indiv month numbers pic](https://user-images.githubusercontent.com/31935414/39829768-71fd0412-538d-11e8-8e24-471fbb1c1a64.png)

**Comment by WorkMAE** [comment]
This is now resolved in the DEV version and will be pushed to the PROD version for tonight's release, it now uses the filters that are applied when showing the data with the following exceptions:

1) YTD data for BR and Client Visists is still displayed
2) YTD Score is static and shows the YTD Total score regardless of filter

![image](https://user-images.githubusercontent.com/31932842/39886900-d402d3a4-545e-11e8-80f4-33ef6a292f79.png)
