### ISSUE TITLE
SAM - Manager and SAM View Numbers don't match

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#49]
Here are two view of the same data.  One is the manager view and one is the SAM view.  As you can see the numbers do not match month to month.

Manager View

![manager view match error pic](https://user-images.githubusercontent.com/31935414/39829936-f2c215ba-538d-11e8-9e88-0407fffb511a.png)

SAM View

![sam view match error pic](https://user-images.githubusercontent.com/31935414/39829959-fd4f31ac-538d-11e8-8442-09b9fbb5aab7.png)

**Comment by WorkMAE** [comment]
This was resolved in one of the later fixes. It resulted from lists being different between Team Lead and SAMs
