### ISSUE TITLE
SM-SAM module does not allow data inputs to be saved

### ISSUE THREAD

**Issue by WorkMAE** [WorkMAE/AMProject#5]
Pending Fix in version 0.58a: all items are defaulted to 0 if they are NULL.
Will close once confirmed fixed.

**Comment by kartikbshukla** [comment]
tested with SAM and functionality working.  Need to verify if data saved properly in backend database.

**Comment by kartikbshukla** [comment]
confirmed from admin view that data shows up.  this issue can be marked fixed.

**Comment by WorkMAE** [comment]
Fixed
