### ISSUE TITLE
ALL - Month Labels to show which month(s) are selected

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#52]
When a single month is selected, I would suggest that month name replaces the “Months” labels.  So if April is selected, it would show April Completed and YTD Completed.  If multiple months are selected, then Months Completed and YTD Completed would be the titles.

This should be mirrored in any Excel output.

_Some representation to indicate which months are selected would be ideal, but does not necessarily need to work exactly this way.  Whichever is the easiest most efficient way to do this will be fine. -KS_

**Comment by WorkMAE** [comment]
CEM Score - Curr Month now shows whatever month the score is for instead of "Month" based on the filters.

![image](https://user-images.githubusercontent.com/31932842/40193867-964b50fe-59d6-11e8-82a8-405a893103d7.png)
