### ISSUE TITLE
ALL (Clients View) - Modals are all blank

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#55]
When clicking on numbers all modals are blank and don't show additional data.  Screenshot shows BR, but it's all categories.

![br modal pic](https://user-images.githubusercontent.com/31935414/39832669-d983c6c2-5395-11e8-90cc-fa8f1fa12967.PNG)

**Comment by WorkMAE** [comment]
This is now resolved, there were some index mismatches on the header rows in the Client View which were not setting the proper headers for lookup.

![image](https://user-images.githubusercontent.com/31932842/39882109-eb43a740-5450-11e8-8668-0d3a10399129.png)
