### ISSUE TITLE
TL (SAM View) - BR Survey Modal is blank

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#56]
Business Review data does not show up.

![business review survey pic](https://user-images.githubusercontent.com/31935414/39833547-5703c032-5398-11e8-89db-ab5debd611a6.PNG)

**Comment by WorkMAE** [comment]
This is now fixed in the DEV version and will be updated in tonight's release.
BR Surveys were not using the proper month filters and instead were using the current month

![image](https://user-images.githubusercontent.com/31932842/39881889-393d4ba0-5450-11e8-870f-7be4670a070e.png)
