### ISSUE TITLE
TL (Client View) - Clicking on specific client number brings up all clients

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#57]
When I click on a specific client's metrics (in this example Incitec Pivot's Other Client Engagements) it doesn't just bring up Incitec Pivot's info, but all clients.  This is across all categories not just Other Client Engagements.

![incitec pivot screengrab](https://user-images.githubusercontent.com/31935414/39833830-33a82500-5399-11e8-8c6b-a285a0dff822.PNG)

![oth client eng screengrab](https://user-images.githubusercontent.com/31935414/39833850-4146d166-5399-11e8-8527-2eb41bf8e8f1.PNG)

**Comment by WorkMAE** [comment]
This is now fixed in the DEV version.  Will be released in tonight's fixes.  Now filter the data by client before getting the data.

![image](https://user-images.githubusercontent.com/31932842/39878420-4ea32924-5446-11e8-8ee4-cf44117b862c.png)
