### ISSUE TITLE
TL (Client View) - Previous View button doesn't work in modal

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#58]
I clicked on Trent's name to bring up SAM By Month modal and then clicked on Complex Projects.  Then when I clicked Previous View button, it didn't take me back to the SAM By Month modal screen.

![sam by month screengrab](https://user-images.githubusercontent.com/31935414/39834205-35fc2b8e-539a-11e8-82a0-b5fdc115a102.PNG)

![cmplx project modal screengrab](https://user-images.githubusercontent.com/31935414/39834210-39dcfee0-539a-11e8-8012-c150b3970841.PNG)

**Comment by WorkMAE** [comment]
This is now resolved, and basically adds the previous headings, table name and row to an array that it goes through to get back to the proper table.  Working on adding modal titles in so the title shows properly and then this will be fully resolved.

**Comment by WorkMAE** [comment]
Modal titles now work as well, closing issue
