### ISSUE TITLE
ALL  - SAM By Month Modal doesn't show SAM Name

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#59]
SAM Name should show up in the modal so user knows which SAM they are viewing.  

![sam by month screengrab](https://user-images.githubusercontent.com/31935414/39834278-6f386cdc-539a-11e8-9341-b160628b6c36.PNG)

**Comment by WorkMAE** [comment]
Now fixed in the DEV version will be pushed in tonight's release.

![image](https://user-images.githubusercontent.com/31932842/39877825-e8110b50-5444-11e8-8adf-d5013e6ef7e0.png)
