### ISSUE TITLE
ALL - Text Overflow BR Survey Modal

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#64]
Client email overflows into Survey Sent Date column.

Can we make sure all columns are adjusted for text overflow?

![text overflow br survey](https://user-images.githubusercontent.com/31935414/39889775-d07e778a-5466-11e8-93fb-3050896f2c7d.PNG)

**Comment by WorkMAE** [comment]
Yeah I have noticed this as well...I think its occurring because its a long string of text with no breaks in it and so it doesn't automatically move it to the next line...I will have to look into either putting a space in at the @ symbol or wrapping it on the cell

**Comment by WorkMAE** [comment]
This is now fixed in DEV, will be released in PROD tonight--changed some CSS settings to make text wrap inside the table cells

![image](https://user-images.githubusercontent.com/31932842/39892759-b39bcfc4-546f-11e8-94f1-a19062780a37.png)
