### ISSUE TITLE
ALL - YTD & Current Month Scores do not match in SAM View and Client View

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#65]
**SAM View Scores**

![sam_view_curr_ytd_scores](https://user-images.githubusercontent.com/31935414/39890502-f86966f4-5468-11e8-9c05-39fe1b898469.PNG)

**Client View Scores**

![client_view_curr_ytd_scores](https://user-images.githubusercontent.com/31935414/39890518-05ff549a-5469-11e8-9922-5056ac55cc2c.PNG)

**Comment by WorkMAE** [comment]
This should now be resolved --- was using wrong count of clients in both views

![image](https://user-images.githubusercontent.com/31932842/39894567-4af99b08-5475-11e8-8761-0a5f222daa01.png)

**Comment by kartikbshukla** [comment]
the scores are still different between SAM and Client view.

**Comment by WorkMAE** [comment]
Found an issue where the NFI and NII points weren't being tallied for the year properly and instead using the singular monthly value.  This is now fixed and the scores match:

Client View Scores:

![image](https://user-images.githubusercontent.com/31932842/39950879-d9fa9252-5552-11e8-8d18-6193004ed59a.png)

SAM View Scores:
![image](https://user-images.githubusercontent.com/31932842/39950888-eaa34d2e-5552-11e8-84f1-649430faa01e.png)
