### ISSUE TITLE
ALL - BR Survey Count not correct

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#67]
- Kim Padgett shows 2 but she has 3 surveys

- Trent shows 4 but he has 6 surveys

**Comment by WorkMAE** [comment]
This is a mismatch between the BR Survey MGRPNUM and her not being assigned that client in the ClientFile...one of two things:

1) Either the MGRPNUM is wrong in the BR Survey file
2) That client isn't assigned to her in the Client File and it won't show until it is.

This is on them to clean up their data, nothing is wrong on my end.
