### ISSUE TITLE
SAM and TL Roles don't match

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#68]
There are differences in numbers when I look at it from Team Lead view vs SAM view.  BR survey doesn't show up in SAM view but it does in Team Lead view.

Trent's SAM View:

![trent sam view](https://user-images.githubusercontent.com/31935414/40515345-770d10de-5f7a-11e8-8457-e85c51d0bea2.png)

Trent TL View:

![trent tl view](https://user-images.githubusercontent.com/31935414/40515355-812176c8-5f7a-11e8-94cb-d428a81ef86f.PNG)

**Comment by WorkMAE** [comment]
Cannot reproduce this issue...all BR Surveys show fine across all views for me as both a team lead in SAM/TL View and as a SAM
