### ISSUE TITLE
SM - Calculate scores at logon and on return to homescreen *HIGH PRIORITY*

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#7]

**Comment by WorkMAE** [comment]
This should be resolved in version 0.95...scores will now re-calc on login for SAM's only.

**Comment by maerman** [comment]
This is fixed in version 1.0a---all views recalculate on the fly,  admin views included when you choose a different user.

**Comment by WorkMAE** [comment]
As of Version 1.0a all views now calculate on the fly including the admin views where you change between users.
