### ISSUE TITLE
SM - save to backend database every time user hits save button in client drill down

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#8]
or add overall save button on home screen.

**Comment by WorkMAE** [comment]
This will be included in the next release, version 0.95.  SAM's will automatically update both locally and directly to the DB when they hit the Save button in the update form.

**Comment by WorkMAE** [comment]
This has been fixed and is live as of 0.95a...all saves to DB now write directly to the Backend DB.
